

import { Note, Mood } from './types';

export const APP_NAME = "Chronos";

export const TRANSLATIONS = {
  en: {
    appName: "Chronos",
    systemActive: "System Active",
    memories: "MEMORIES",
    emptyState: "Time is empty. Start recording.",
    captureThought: "Capture Thought",
    placeholder: "What's on your mind? (⌘ + Enter to save)",
    record: "Record",
    chars: "chars",
    aiDisclaimer: "AI will analyze and organize this for you.",
    analyzing: "Analyzing...",
    untitled: "Untitled Entry",
    settings: "SYSTEM_CONFIG",
    filter: "DATA_FILTER",
    language: "Language",
    crtEffect: "CRT Visuals",
    soundEffect: "Mech. Sfx",
    hapticFeedback: "Haptics",
    volume: "Volume",
    soundType: "Sound Type",
    soundTypes: {
      MECHANICAL: "Mechanical",
      RETRO: "8-Bit",
      SOFT: "Bubble"
    },
    imageStylization: "Retro Img Filter",
    screenshotMode: "Screenshot Mode",
    cardMargin: "Card Margin",
    splitTitleMood: "Split Title/Mood",
    smartAnalysisMode: "Smart Analysis",
    targetNote: "Target Memory",
    dataManagement: "Data I/O",
    exportData: "EXPORT_DB",
    importData: "IMPORT_DB",
    importSuccess: "DATA_RESTORED",
    importError: "DATA_CORRUPT",
    invalidFormat: "INVALID_JSON_FORMAT",
    on: "ON",
    off: "OFF",
    delete: "PURGE_DATA",
    confirmDelete: "WARNING: Irreversible data deletion.\nAre you sure you want to purge this memory block?",
    cancel: "CANCEL",
    confirm: "CONFIRM",
    edit: "MODIFY_LOG",
    saveChanges: "COMMIT_CHANGES",
    discardChanges: "DISCARD",
    editMode: "EDIT_MODE_ACTIVE",
    addImage: "ADD_IMG",
    photos: "VISUAL_ATTACHMENTS",
    closeImage: "CLOSE_VIEWER",
    pulledOut: "PULLED_OUT // CLICK_TO_READ",
    putBack: "PUT BACK",
    clickToRecord: "INIT_DATA_STREAM [↘]",
    settingsTips: {
      language: "Switch system interface language.",
      smartAnalysis: "AI auto-generates tags, moods & summaries.",
      crt: "Simulate curved screen & scanline artifacts.",
      imageStyle: "Apply monochrome & noise filters to photos.",
      sound: "Enable mechanical UI interaction sounds.",
      haptic: "Enable tactile vibration feedback on interaction.",
      screenshot: "Optimized clean view for sharing memories.",
      data: "Backup or restore your local database."
    },
    filterModal: {
      title: "QUERY_PARAMETERS",
      dateRange: "TEMPORAL_RANGE",
      tags: "TAG_SELECTOR",
      tagMode: "LOGIC_GATE",
      modeAny: "MATCH_ANY (OR)",
      modeAll: "MATCH_ALL (AND)",
      apply: "EXECUTE_FILTER",
      reset: "RESET_QUERY",
      noTags: "NO_TAGS_AVAILABLE",
      from: "FROM",
      to: "TO"
    },
    labels: {
      title: "SUBJECT_LINE",
      date: "TIMESTAMP_OVERRIDE",
      mood: "EMOTIONAL_STATUS",
      tags: "TAG_MATRIX (comma separated)",
      content: "DATA_CONTENT"
    },
    moods: {
      [Mood.NEUTRAL]: "Neutral",
      [Mood.HAPPY]: "Happy",
      [Mood.SAD]: "Sad",
      [Mood.FOCUSED]: "Focused",
      [Mood.EXCITED]: "Excited",
      [Mood.ANXIOUS]: "Anxious"
    }
  },
  zh: {
    appName: "Chronos",
    systemActive: "系统在线",
    memories: "条记忆",
    emptyState: "时光空空如也，开始记录吧。",
    captureThought: "捕捉灵感",
    placeholder: "此刻在想什么？(⌘ + Enter 保存)",
    record: "记录",
    chars: "字",
    aiDisclaimer: "AI 将自动分析并为您整理。",
    analyzing: "分析中...",
    untitled: "无标题",
    settings: "系统设置",
    filter: "数据筛选",
    language: "界面语言",
    crtEffect: "CRT 特效",
    soundEffect: "机械音效",
    hapticFeedback: "触觉反馈",
    volume: "音量",
    soundType: "音效类型",
    soundTypes: {
      MECHANICAL: "机械轴",
      RETRO: "8-Bit",
      SOFT: "气泡音"
    },
    imageStylization: "复古图像滤镜",
    screenshotMode: "截图模式",
    cardMargin: "卡片边距",
    splitTitleMood: "分离标题/心情",
    smartAnalysisMode: "智能分析模式",
    targetNote: "目标记忆",
    dataManagement: "数据读写",
    exportData: "导出备份",
    importData: "导入数据",
    importSuccess: "数据恢复成功",
    importError: "数据损坏或无效",
    invalidFormat: "JSON 格式错误",
    on: "开启",
    off: "关闭",
    delete: "清除数据",
    confirmDelete: "警告：数据删除不可逆。\n确定要清除此内存块吗？",
    cancel: "取消操作",
    confirm: "确认执行",
    edit: "修改记录",
    saveChanges: "保存变更",
    discardChanges: "放弃修改",
    editMode: "编辑模式已激活",
    addImage: "添加图像",
    photos: "视觉附件",
    closeImage: "关闭视图",
    pulledOut: "已抽出 // 点击阅读",
    putBack: "放回",
    clickToRecord: "点击记录灵感 [↘]",
    settingsTips: {
      language: "切换系统界面显示的语言。",
      smartAnalysis: "AI 自动生成摘要、情绪分析与标签。",
      crt: "模拟老式显像管屏幕与扫描线效果。",
      imageStyle: "为照片应用单色噪点复古滤镜。",
      sound: "启用机械键盘与系统交互音效。",
      haptic: "启用交互时的震动触觉反馈。",
      screenshot: "适合分享与留存的纯净视图模式。",
      data: "备份导出或恢复本地数据库。"
    },
    filterModal: {
      title: "筛选参数",
      dateRange: "时间范围",
      tags: "标签选择",
      tagMode: "逻辑门",
      modeAny: "包含任意 (OR)",
      modeAll: "包含所有 (AND)",
      apply: "执行筛选",
      reset: "重置条件",
      noTags: "无可用标签",
      from: "起始",
      to: "终止"
    },
    labels: {
      title: "主题摘要",
      date: "时间戳覆写",
      mood: "情绪状态",
      tags: "标签矩阵 (逗号分隔)",
      content: "数据内容"
    },
    moods: {
      [Mood.NEUTRAL]: "平静",
      [Mood.HAPPY]: "开心",
      [Mood.SAD]: "低落",
      [Mood.FOCUSED]: "专注",
      [Mood.EXCITED]: "兴奋",
      [Mood.ANXIOUS]: "焦虑"
    }
  }
};

export const INITIAL_NOTES: Note[] = [];